### ISSUE TITLE
Hub expects parameters "hub_mode", "hub_callback" etc. instead of the spec's "hub.mode", "hub.callback"

### ISSUE THREAD

**Issue by tonyg** [aaronpk/pubsub.rocks#4]
The pubsub.rocks hub expects parameters "hub_mode", "hub_callback" etc. instead of the spec's "hub.mode", "hub.callback". Could the code be wrong? Or is it anticipating an upcoming spec change?

**Comment by aaronpk** [comment]
Were you able to determine this by using the site? The crazy thing is due to legacy reasons, PHP converts . to _ in form parameters, so I have to write the code to check for _ instead. Sending . should make this code behave according to the soec.

**Comment by tonyg** [comment]
Wow, that's a pretty hair-raising PHP feature :-)

Yes, this was from the site: I was sending a POST to `https://pubsub.rocks/subscriber/100/PPOqguc4svUKE6EJ0pDa/hub` with body

    hub.callback=http%3A%2F%2Flocalhost%3A7827%2Fsub%2Faa84fc2096d5401f2f1b80e438e66895&hub.mode=subscribe&hub.topic=https%3A%2F%2Fpubsub.rocks%2Fsubscriber%2F100%2FPPOqguc4svUKE6EJ0pDa

(ignore the `localhost` callback URL for now :-) ) and got a response

    (web-response-header 400 "Bad Request" #f "application/json"
      ((server . "nginx/1.9.10")
       (date . "Mon, 21 Nov 2016 05:17:37 GMT")
       (content-type . "application/json")
       (content-length . "39")
       (connection . "close")
       (x-powered-by . "PHP/5.6.21-1+donate.sury.org~trusty+4")))
    #"{\"error\":\"invalid_mode\",\"type\":\"error\"}"

**Comment by tonyg** [comment]
Hmm, it doesn't work with body

    hub_callback=http%3A%2F%2Flocalhost%3A7827%2Fsub%2Fc5961d18313b4e1824105bcf0b5a8bf1&hub_mode=subscribe&hub_topic=https%3A%2F%2Fpubsub.rocks%2Fsubscriber%2F100%2FrxgMlP3IdpwHN1zWrYfH

either. Maybe there's something else wrong. I'll keep experimenting.

**Comment by tonyg** [comment]
OK, got it: I was missing a content-type header. Adding "Content-Type: application/x-www-form-urlencoded" lets me get through to the next stage.

In the 20 Oct draft, I see "This request has a Content-Type of application/x-www-form-urlencoded", which I'd overlooked. In fact, my first reading of it is that the sentence tells me how to format the body, but doesn't directly tell me anything about whether or which Content-Type header I should or must include. Perhaps strengthening this to a SHOULD or a MUST would help. I'll file a spec issue.

**Comment by aaronpk** [comment]
I've been using `.` when testing this, and also I've tested this site's publisher with its own subscriber, so I'm pretty sure the code is fine. Double check you're sending the correct content type header and encoding everything properly. Here's an example with curl:

```
curl https://pubsub.rocks/subscriber/100/NNdqzi6zU64rz7qihG1f/hub -d hub.mode=subscribe
```

```
HTTP/1.1 400 Bad Request
Server: nginx/1.9.10
Date: Mon, 21 Nov 2016 19:48:51 GMT
Content-Type: application/json
Content-Length: 120
Connection: keep-alive
X-Powered-By: PHP/5.6.21-1+donate.sury.org~trusty+4

{
  "error": "missing_params",
  "error_description": "The request is missing the callback and topic parameters",
  "type": "error"
}
```

**Comment by aaronpk** [comment]
hah you beat me to it by a couple seconds! Glad you figured it out.
